import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import ClientShell from "./ClientShell";
import NextTopLoader from "nextjs-toploader";
import { CartProvider } from "../context/CartContext";
import { ConvexClientProvider } from "./ConvexClientProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} font-sans antialiased`}>
        <NextTopLoader color="#D87D4A" height={4} showSpinner={false} />
        <CartProvider>
          <ClientShell>  <ConvexClientProvider>{children}</ConvexClientProvider></ClientShell>
        </CartProvider>
      </body>
    </html>
  );
}
